@baseUrl = http://localhost:3000

### Create a pizza by using the admin account
#### First login as the admin
##### Define a request variable nammed admin
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

### 2.1) get a new game without filtering the level
GET {{baseUrl}}/games/start

### 2.1) get a new game for a specific level
GET {{baseUrl}}/games/start?level=hard

### 2.2) create a new game result for a user
# @name admin
POST {{baseUrl}}/games
Content-Type: application/json
Authorization: {{admin.response.body.token}}

{
  "username":"ssalut",
  "score":3 
}

#### 2.2.b) try to create the game result by provinding a wrong score for a user
# @name admin
POST {{baseUrl}}/games
Content-Type: application/json
Authorization: {{admin.response.body.token}}

{
  "username":"Nicoco",
  "score":5 
}